'use client'
import Head from 'next/head'
import axios from 'axios'
import { useEffect } from 'react'
import CustomTextField from 'src/components/text-field'

export default function Home() {
  const fetchApiUser = async () => {
    await axios.get("http://localhost:3001/api/users?limit=10&page=1&order=created%20asc").then((res) => {
      console.log("res", {res});
      
    })
  }

  useEffect( () => {
    fetchApiUser()
  },[])

  return (
    <>
      <Head>
        <title>Lập trình thật dễ</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <CustomTextField id="outlined-basic" label="Outlined">Hello world updated</CustomTextField>
    </>
  )
}
