'use client'
import { NextPage } from 'next'
import Head from 'next/head'
import { types } from 'util'

type TProps = {
  
}

const Login: NextPage<TProps> = () => {
  return (
    <>
      <Head>
        <title>Lập trình thật dễ</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box sx={ {margin: 6, width: "200px"} }>
        <CustomTextField id="outlined-basic" label="Outlined" />
      </Box>
    </>
  )
}